### ISSUE TITLE
[FEAT] read/writeUInt64

### ISSUE THREAD

**Issue by theLMGN** [Dekkonot/bitbuffer#34]
It seems interesting that a data storage system for Roblox can't even store Roblox IDs [which have been over 32-bits for over a year](https://devforum.roblox.com/t/userids-are-going-over-32-bit-on-december-7th/903982).

It would great to see a read/writeUInt64 function added to this library!

Thanks!

**Comment by Dekkonot** [comment]
This was a deliberate choice. Numbers in Lua are doubles, which have 58 significant bits. Without some sort of bigint implementation (which is well outside of scope), it's impossible to actually have 64 bit integers. I'd rather not lie to people about the precision of integers because it seems like a footgun waiting to happen.

**Comment by theLMGN** [comment]
Thanks for your answer. Do you reckon using Float64 is a good substitute? (I'm not too familiar with binary data types so I'm not sure if that's the same as the Lua number type 😅 )

**Comment by Dekkonot** [comment]
Float64 is another name for a double, so I would use it if you need full precision. Its not interchangable with an Int64 necessarily, but with any number below 2^53 it is.
